import React from "react";
import { Panel } from "@epam/promo";
import * as css from "./ReworkTable.scss";

export function ReworkTable() {
    return (
        <Panel
            background="white"
            rawProps={{ role: 'region', tabIndex: 0, "aria-labelledby": 'caption' }}
            cx={css.Wrapper}
            shadow
        >
            <table>
                <caption id='caption'>Baseball numbers</caption>
                <thead>
                    <tr>
                        <th>Teams</th>
                        <th>1</th>
                        <th>2</th>
                        <th>3</th>
                        <th>4</th>
                        <th>5</th>
                        <th>6</th>
                        <th>7</th>
                        <th>8</th>
                        <th>9</th>
                        <th>10</th>
                        <th>11</th>
                        <th>Runs</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>Milwaukee Brewers</th>
                        <td>3</td>
                        <td>3</td>
                        <td>0</td>
                        <td>2</td>
                        <td>2</td>
                        <td>0</td>
                        <td>4</td>
                        <td>4</td>
                        <td>4</td>
                        <td>22</td>
                        <td>22</td>
                        <td>22</td>
                    </tr>
                    <tr>
                        <th>Los Angles Dodgers</th>
                        <td>1</td>
                        <td>1</td>
                        <td>0</td>
                        <td>4</td>
                        <td>1</td>
                        <td>2</td>
                        <td>0</td>
                        <td>3</td>
                        <td>4</td>
                        <td>16</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>New York Mets</th>
                        <td>2</td>
                        <td>3</td>
                        <td>1</td>
                        <td>1</td>
                        <td>2</td>
                        <td>4</td>
                        <td>2</td>
                        <td>2</td>
                        <td>1</td>
                        <td>18</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>St. Louis Cardinals</th>
                        <td>0</td>
                        <td>0</td>
                        <td>3</td>
                        <td>0</td>
                        <td>2</td>
                        <td>3</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>8</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Houston Astros</th>
                        <td>3</td>
                        <td>4</td>
                        <td>2</td>
                        <td>1</td>
                        <td>4</td>
                        <td>2</td>
                        <td>0</td>
                        <td>2</td>
                        <td>2</td>
                        <td>20</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Toronto Blue Jays</th>
                        <td>0</td>
                        <td>0</td>
                        <td>3</td>
                        <td>1</td>
                        <td>1</td>
                        <td>0</td>
                        <td>3</td>
                        <td>0</td>
                        <td>3</td>
                        <td>11</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Boston Red Sox</th>
                        <td>0</td>
                        <td>4</td>
                        <td>4</td>
                        <td>4</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>4</td>
                        <td>4</td>
                        <td>23</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Chicago Cubs</th>
                        <td>2</td>
                        <td>0</td>
                        <td>0</td>
                        <td>4</td>
                        <td>0</td>
                        <td>2</td>
                        <td>3</td>
                        <td>3</td>
                        <td>1</td>
                        <td>15</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Philadelphia Phillies</th>
                        <td>4</td>
                        <td>4</td>
                        <td>4</td>
                        <td>2</td>
                        <td>0</td>
                        <td>4</td>
                        <td>4</td>
                        <td>2</td>
                        <td>3</td>
                        <td>27</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Chicago White Sox</th>
                        <td>3</td>
                        <td>2</td>
                        <td>2</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>1</td>
                        <td>11</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>San Diego Padres</th>
                        <td>3</td>
                        <td>2</td>
                        <td>2</td>
                        <td>4</td>
                        <td>1</td>
                        <td>0</td>
                        <td>3</td>
                        <td>0</td>
                        <td>1</td>
                        <td>16</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Cleveland Indians</th>
                        <td>3</td>
                        <td>4</td>
                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>0</td>
                        <td>3</td>
                        <td>2</td>
                        <td>4</td>
                        <td>22</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>San Francisco Giants</th>
                        <td>1</td>
                        <td>3</td>
                        <td>2</td>
                        <td>3</td>
                        <td>1</td>
                        <td>4</td>
                        <td>1</td>
                        <td>2</td>
                        <td>2</td>
                        <td>19</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Cincinatti Reds</th>
                        <td>1</td>
                        <td>2</td>
                        <td>0</td>
                        <td>0</td>
                        <td>4</td>
                        <td>2</td>
                        <td>0</td>
                        <td>1</td>
                        <td>0</td>
                        <td>10</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Minnesota Twins</th>
                        <td>1</td>
                        <td>4</td>
                        <td>2</td>
                        <td>0</td>
                        <td>4</td>
                        <td>3</td>
                        <td>4</td>
                        <td>4</td>
                        <td>0</td>
                        <td>22</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Tampa Bay Rays</th>
                        <td>1</td>
                        <td>4</td>
                        <td>2</td>
                        <td>1</td>
                        <td>3</td>
                        <td>0</td>
                        <td>1</td>
                        <td>4</td>
                        <td>3</td>
                        <td>19</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Miami Marlins</th>
                        <td>3</td>
                        <td>3</td>
                        <td>2</td>
                        <td>3</td>
                        <td>3</td>
                        <td>1</td>
                        <td>1</td>
                        <td>3</td>
                        <td>0</td>
                        <td>19</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Oakland Athletics</th>
                        <td>0</td>
                        <td>4</td>
                        <td>3</td>
                        <td>1</td>
                        <td>4</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>1</td>
                        <td>4</td>
                        <td>16</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Detroit Tigers</th>
                        <td>4</td>
                        <td>3</td>
                        <td>0</td>
                        <td>0</td>
                        <td>2</td>
                        <td>3</td>
                        <td>1</td>
                        <td>1</td>
                        <td>4</td>
                        <td>18</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Pittsburgh Pirates</th>
                        <td>1</td>
                        <td>1</td>
                        <td>4</td>
                        <td>3</td>
                        <td>3</td>
                        <td>1</td>
                        <td>1</td>
                        <td>3</td>
                        <td>1</td>
                        <td>18</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Seattle Mariners</th>
                        <td>1</td>
                        <td>2</td>
                        <td>4</td>
                        <td>2</td>
                        <td>2</td>
                        <td>0</td>
                        <td>2</td>
                        <td>0</td>
                        <td>1</td>
                        <td>14</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <th>Atlanta Braves</th>
                        <td>4</td>
                        <td>1</td>
                        <td>0</td>
                        <td>3</td>
                        <td>3</td>
                        <td>2</td>
                        <td>2</td>
                        <td>4</td>
                        <td>1</td>
                        <td>20</td>
                        <td>4</td>
                        <td>16</td>
                    </tr>
                </tbody>
            </table>
        </Panel>
    );
}
